# Collector specific configuration
IDPS_URL: "https://dtmapi.iom.int/v3/displacement/admin{admin_level}?Admin0Pcode={iso3}"

COUNTRIES_URL: "https://dtmapi.iom.int/v3/displacement/country-list"

OPERATION_STATUS_URL: "https://dtmapi.iom.int/v3/displacement/operation-list"

tags:
  - conflict-violence
  - displacement
  - forced displacement
  - internally displaced persons-idp

qc_resource_filename: data_for_quickcharts.csv

qc_resource_data:
  name: Data for QuickCharts
  description: Filtered and aggregated data used to create QuickCharts

qc_countries:
  - AFG
  - HTI
  - TCD

admin_levels:
  - 0
  - 1
  - 2

headers:
  - id
  - operation
  - admin0Name
  - admin0Pcode
  - admin1Name
  - admin1Pcode
  - admin2Name
  - admin2Pcode
  - adminLevel
  - numPresentIdpInd
  - reportingDate
  - yearReportingDate
  - monthReportingDate
  - roundNumber
  - displacementReason
  - numberMales
  - numberFemales
  - idpOriginAdmin1Name
  - idpOriginAdmin1Pcode
  - assessmentType
  - operationStatus

hapi_resource_data:
  name: "Global Affected People: Internally-Displaced Persons"
  description: "IDPs data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/affected_people/#internally-displaced-persons) for more information"
  p_coded: True

hapi_headers:
  - location_code
  - has_hrp
  - in_gho
  - provider_admin1_name
  - provider_admin2_name
  - admin1_code
  - admin1_name
  - admin2_code
  - admin2_name
  - admin_level
  - operation
  - assessment_type
  - population
  - reporting_round
  - reference_period_start
  - reference_period_end
  - dataset_hdx_id
  - resource_hdx_id
  - warning
  - error
